import React, { useState } from 'react';
import { AlertTriangle, Battery, Camera, Check, ChevronDown, ClipboardCheck, CloudSun, Droplets, Flashlight, MapPin, RotateCcw, ShieldCheck, ThermometerSun, Wind } from 'lucide-react';
import { LocationType } from '../types/pose';
import { LOCATIONS } from '../data/locations';

const BASE = ['باتری دوربین و گوشی', 'کارت حافظه و فضای خالی', 'لنز و دستمال میکروفایبر', 'سه‌پایه یا گیمبال', 'رفلکتور یا نور پرکن', 'آب، کفش مناسب و مسیر امن'];
const EXTRA: Record<LocationType,string[]> = {
  'جنوب':['محافظت از لنز در برابر گردوغبار و گرما','آب کافی و کلاه برای گرمای شدید','بررسی مسیر پیاده در نخلستان'],
  'ساحل':['محافظت از لنز در برابر نمک و شن','بررسی موج و مسیر برگشت آب','فیلتر ND برای نور سخت'],
  'شمال':['دستمال ضدبخار لنز','کفش ضدلغزش برای مسیر خیس','بررسی مه و نور کم جنگل'],
  'کویر':['تعویض لنز فقط داخل خودرو یا کیف','آب کافی و محافظ گردوغبار','مشخص کردن مسیر برگشت قبل از غروب'],
  'شهر':['هماهنگی مجوز عکاسی در اماکن خصوصی','توجه به تردد خودرو و عابران','باتری اضافه برای جابه‌جایی سریع بین لوکیشن'],
  'باغ عمارت':['هماهنگی زمان ورود و مجوز عکاسی','بررسی پله، حوض و مسیرهای عبور','حذف وسایل اضافه از کادر معماری'],
};
export const EmergencyView: React.FC = () => { const [loc,setLoc]=useState<LocationType>('باغ عمارت'); const [done,setDone]=useState<Record<string,boolean>>({}); const [open,setOpen]=useState(true); const items=[...BASE,...EXTRA[loc]]; const toggle=(x:string)=>setDone(d=>({...d,[x]:!d[x]})); const reset=()=>setDone({}); return <div className="space-y-4">
  <section className="card p-5" style={{borderColor:'color-mix(in srgb, var(--color-rose) 45%, var(--color-line))'}}><span className="pill" style={{color:'var(--color-rose)'}}><AlertTriangle className="w-3 h-3"/> حالت اضطراری سر صحنه</span><h1 className="text-[22px] font-extrabold mt-3">قبل از ضبط،<br/><span style={{color:'var(--color-rose)'}}>ریسک‌ها را حذف کن.</span></h1><p className="text-[12px] text-muted leading-relaxed mt-2">این چک‌لیست آفلاین است و برای جلوگیری از خراب شدن پروژه، تجهیزات، شرایط محیط و ایمنی را سریع مرور می‌کند.</p></section>
  <div className="flex gap-1.5 overflow-x-auto no-scrollbar">{LOCATIONS.map(l=><button key={l.key} onClick={()=>{setLoc(l.key);setDone({})}} className={`pill ${loc===l.key?'pill-on':''}`}><l.icon className="w-3.5 h-3.5" /> {l.key}</button>)}</div>
  <div className="card overflow-hidden"><button onClick={()=>setOpen(v=>!v)} className="w-full p-4 flex items-center gap-3 text-right"><span className="w-9 h-9 rounded-xl flex items-center justify-center" style={{background:'color-mix(in srgb, var(--color-rose) 14%, transparent)',color:'var(--color-rose)'}}><ClipboardCheck className="w-4 h-4"/></span><span className="flex-1"><b className="block text-[14px]">چک‌لیست {loc}</b><small className="text-[10px] text-muted">{items.filter(x=>done[x]).length} از {items.length} مورد بررسی شده</small></span><ChevronDown className="w-4 h-4 text-faint" style={{transform:open?'rotate(180deg)':'none'}}/></button>{open&&<div className="px-4 pb-4 space-y-2">{items.map((x,i)=><button key={x} onClick={()=>toggle(x)} className="w-full flex items-center gap-2.5 p-2.5 rounded-2xl border text-right" style={{borderColor:done[x]?'var(--color-teal)':'var(--color-line)',background:done[x]?'color-mix(in srgb, var(--color-teal) 10%, transparent)':'transparent'}}><span className="w-5 h-5 rounded-md border flex items-center justify-center shrink-0" style={{borderColor:done[x]?'var(--color-teal)':'var(--color-faint)',background:done[x]?'var(--color-teal)':'transparent'}}>{done[x]&&<Check className="w-3.5 h-3.5 text-bg"/>}</span><span className="text-[12px]">{x}</span></button>)}<button onClick={reset} className="text-[10px] text-gold font-bold flex items-center gap-1 mt-2"><RotateCcw className="w-3 h-3"/> پاک کردن تیک‌ها</button></div>}</div>
  <div className="grid grid-cols-2 gap-2.5"><Info icon={Battery} title="باتری" text="حداقل ۷۰٪ دوربین، گوشی و گیمبال"/><Info icon={CloudSun} title="نور" text={`نور مناسب ${loc} را قبل از حرکت چک کن`}/><Info icon={ThermometerSun} title="شرایط بدن" text="آب، استراحت کوتاه و کفش مناسب"/><Info icon={ShieldCheck} title="ایمنی" text="حرکت را با نسخه ساده‌تر شروع کن"/></div>
 </div> }
const Info:React.FC<{icon:React.ElementType;title:string;text:string}>=({icon:Icon,title,text})=><div className="card p-3"><Icon className="w-4 h-4 text-gold"/><b className="block text-[11px] mt-2">{title}</b><p className="text-[10px] text-muted leading-relaxed mt-1">{text}</p></div>;
