import React, { useMemo, useState } from 'react';
import { Dice5, Lightbulb, MapPin, RefreshCw, Sparkles, Users } from 'lucide-react';
import { CategoryType, LocationType, PoseType } from '../types/pose';
import { LOCATIONS } from '../data/locations';
const feelings=['صمیمی','شاد','آرام','باشکوه','طبیعی','دراماتیک']; const cats:CategoryType[]=['عروس و داماد','عروس','داماد','زوج','گروهی']; const types:PoseType[]=['ایستاده','نشسته','راه رفتن','بغل کردن','رمانتیک','رسمی','خلاقانه','حرکتی'];
export const PoseGeneratorView:React.FC=()=>{const [loc,setLoc]=useState<LocationType>('باغ عمارت');const [feel,setFeel]=useState('صمیمی');const [cat,setCat]=useState<CategoryType>('عروس و داماد');const [type,setType]=useState<PoseType>('ایستاده');const [seed,setSeed]=useState(0);const result=useMemo(()=>{const starts=type==='راه رفتن'||type==='حرکتی'?'حرکت را با سه قدم آرام شروع کن':'از یک ایستادن نزدیک و راحت شروع کن';const touch=feel==='صمیمی'?'دست‌ها، شانه یا پیشانی را به شکل طبیعی به هم وصل کن':'هر نفر یک جهت نگاه یا حرکت مشخص داشته باشد';return {title:`${feel} ${type} در ${loc}`,steps:[starts,`بدن ${cat==='عروس و داماد'||cat==='زوج'?'دو سوژه را با زاویه مخالف و وزن روی یک پا':'سوژه را با شانه کمی چرخیده'} بچین`,touch,'در نقطه اوج، ۲ ثانیه مکث کن و یک قاب تمیز بگیر'],say:type==='راه رفتن'?'آرام کنار هم راه بروید و در پایان سه ثانیه بایستید.':'همین حالت را نگه دارید، فقط آرام به هم نگاه کنید.'}},[loc,feel,cat,type,seed]);return <div className="space-y-4">
<section className="card p-5"><span className="pill"><Sparkles className="w-3 h-3 text-gold"/> موتور ساخت ژست آفلاین</span><h1 className="text-[22px] font-extrabold mt-3">با چند انتخاب،<br/><span className="text-gold">ایده تازه بساز.</span></h1><p className="text-[12px] text-muted leading-relaxed mt-2">این موتور از قوانین بدن، ارتباط، حس و لوکیشن ترکیب می‌سازد، نه از اینترنت.</p></section>
<Picker label="لوکیشن" icon={MapPin} options={LOCATIONS.map(x=>x.key)} value={loc} onChange={x=>setLoc(x as LocationType)}/><Picker label="حس عکس" icon={Lightbulb} options={feelings} value={feel} onChange={setFeel}/><Picker label="سوژه" icon={Users} options={cats} value={cat} onChange={x=>setCat(x as CategoryType)}/><Picker label="نوع حرکت" icon={Dice5} options={types} value={type} onChange={x=>setType(x as PoseType)}/>
<section className="card p-4" style={{borderColor:'color-mix(in srgb, var(--color-gold) 50%, var(--color-line))'}}><div className="flex items-center justify-between gap-2"><div><span className="text-[10px] font-extrabold text-gold">پیشنهاد ترکیبی</span><h2 className="text-[17px] font-extrabold mt-1">{result.title}</h2></div><button onClick={()=>setSeed(x=>x+1)} className="p-2 rounded-xl text-gold" style={{background:'color-mix(in srgb, var(--color-gold) 12%, transparent)'}}><RefreshCw className="w-4 h-4"/></button></div><ol className="space-y-2 mt-4">{result.steps.map((x,i)=><li key={i} className="flex gap-2 text-[12px] leading-relaxed"><b className="text-gold">۰{i+1}</b>{x}</li>)}</ol><div className="mt-4 p-3 rounded-2xl" style={{background:'color-mix(in srgb, var(--color-teal) 10%, transparent)'}}><span className="text-[10px] font-extrabold text-teal">به سوژه بگو</span><p className="text-[12px] leading-relaxed mt-1">{result.say}</p></div></section>
</div>}
const Picker:React.FC<{label:string;icon:React.ElementType;options:string[];value:string;onChange:(x:string)=>void}>=({label,icon:Icon,options,value,onChange})=><div><span className="label flex items-center gap-1.5"><Icon className="w-3.5 h-3.5 text-gold"/>{label}</span><div className="flex gap-1.5 overflow-x-auto no-scrollbar">{options.map(x=><button key={x} onClick={()=>onChange(x)} className={`pill ${value===x?'pill-on':''}`}>{x}</button>)}</div></div>;
