import React, { useState } from 'react';
import { ArrowLeft, BookOpen, Check, ChevronDown, ExternalLink, Lightbulb, Target, WandSparkles } from 'lucide-react';
import { SectionGuide } from '../components/SectionGuide';

const PHASES = [
  { n: '۰۱', label: 'پیش‌نیازها', title: 'قبل از ژست، آدم و صحنه را بخوان', color: 'var(--color-teal)', lessons: [
    ['هدف عکس را مشخص کن', 'قبل از حرکت تصمیم بگیر تصویر باید چه حسی منتقل کند: صمیمیت، قدرت، آرامش، شادی یا شکوه. ژست باید در خدمت داستان و شخصیت سوژه باشد، نه فقط زیبا به نظر برسد. ابتدا مشخص کن عکس برای آلبوم است، قاب عمودی، تصویر معرفی یا لحظه‌ای طبیعی.', 'سه کلمه بنویس: حس، داستان، نقطه تمرکز. بعد یک قاب خالی از لوکیشن پیدا کن و بررسی کن سوژه در آن قاب چه نقشی دارد.'],
    ['نور و پس‌زمینه را بررسی کن', 'جهت نور، سختی سایه، خطوط معماری، رنگ لباس و فضای حرکت، انتخاب ژست را تعیین می‌کنند. سوژه را جایی بگذار که نور صورت را بخواند و پس‌زمینه با بدن و لباس رقابت نکند. پیش از آوردن سوژه، چند قدم جابه‌جا شو و پس‌زمینه را ساده‌تر کن.', 'قبل از صدا زدن سوژه، یک قاب خالی بگیر و سه چیز مزاحم را حذف کن: خطی که از سر رد می‌شود، نور شدید و عنصر اضافی.'],
    ['با سوژه ارتباط بساز', 'بدنِ سوژه قبل از دوربین به اعتماد نیاز دارد. با دستورهای کوچک شروع کن، فضای شخصی را رعایت کن و به جای «خوب باش» یک حرکت دقیق بده. لبخند واقعی از گفت‌وگوی واقعی می‌آید، نه از دستور تکراری لبخند بزن.', 'یک جمله شخصی و یک حرکت ساده آماده کن: قدم آرام، نگاه به یک نقطه یا مرتب کردن لباس. بعد از اولین قاب بازخورد کوتاه و مثبت بده.'],
  ] },
  { n: '۰۲', label: 'اصول پایه', title: 'بدن را از پا تا چشم بساز', color: 'var(--color-gold)', lessons: [
    ['پاها و وزن بدن', 'وزن را روی یک پا بینداز و پای دیگر را سبک نگه دار. دو پای موازی بدن را تخت و بی‌حرکت می‌کند؛ چرخش نرم پنجه و زانو، بدن را زنده‌تر نشان می‌دهد. اول پاها را تنظیم کن، چون بیشتر خطاهای بالاتنه از پایه‌ی ناپایدار می‌آیند.', 'یک ژست را با سه جای پا امتحان کن: وزن روی پای عقب، قدم کوچک به جلو، و پنجه‌ی چرخیده. تغییر را در خط لگن و شانه ببین.'],
    ['لگن، شانه و خط بدن', 'بدن را صاف و خشک نکن. لگن و شانه کمی خلاف جهت هم باشند تا خط S یا مثلث بسازند. فاصله‌ی کم بین بازو و تنه، فرم را خواناتر می‌کند و چرخش سه‌ربع معمولاً حجم بدن را بهتر از نمای کاملاً روبه‌رو نشان می‌دهد.', 'فقط زاویه‌ی شانه را عوض کن، بدون تغییر صورت. سه قاب بگیر و ببین کدام حالت بدن را باریک‌تر و طبیعی‌تر نشان می‌دهد.'],
    ['دست‌ها و انگشت‌ها', 'دست معلق اضطراب می‌سازد. دست را به لباس، دسته‌گل، یقه، دست نفر مقابل یا محیط وصل کن. انگشت‌ها نرم و جدا باشند و کف دست بی‌دلیل رو به دوربین نماند. هر دست باید یا کاری انجام دهد یا با دست دیگر رابطه بسازد.', 'برای هر ژست سه نقطه تماس تعریف کن: دست با لباس، دست با سوژه و دست با محیط. یکی را حذف کن تا قاب شلوغ نشود.'],
    ['چانه، گردن و نگاه', 'چانه کمی جلو و پایین، گردن کشیده و نگاه هدفمند باشد. نگاه مستقیم همیشه بهترین انتخاب نیست؛ نگاه به دست، افق یا نفر مقابل داستان متفاوتی می‌سازد. صورت را بعد از تنظیم بدن و دست‌ها اصلاح کن، نه قبل از آن.', 'اول نگاه را به یک نقطه‌ی مشخص بده، سپس از سوژه بخواه نفسش را نگه ندارد و در همان لحظه شاتر بزن.'],
  ] },
  { n: '۰۳', label: 'ساخت تنوع', title: 'از یک ژست، ده ایده بساز', color: 'var(--color-plum)', lessons: [
    ['ژست پایه را نگه دار', 'برای ساخت تنوع لازم نیست ژست را از صفر عوض کنی. فقط یک متغیر را تغییر بده: نگاه، دست، زاویه، فاصله، ارتفاع دوربین یا حرکت. این روش هم سرعت کار را بالا می‌برد و هم مجموعه‌ای هماهنگ برای آلبوم می‌سازد.', 'فرمول را اجرا کن: ژست پایه + نگاه + دست + زاویه + فاصله + حرکت. هر بار فقط یک عامل را عوض کن تا بدانی چه چیزی نتیجه را تغییر داده است.'],
    ['تعامل بساز', 'برای زوج‌ها تماس باید هدف داشته باشد: دست، شانه، پیشانی، کمر یا نگاه. فاصله‌ی زیاد سرد است و تماس بی‌منطق فرم را خراب می‌کند. اجازه بده تماس، داستان رابطه را تعریف کند و از سوژه نخواهی فقط لبخند مصنوعی بزند.', 'یک ژست را در سه فاصله اجرا کن: بدون تماس، تماس دست و تماس کامل. بین هر نسخه فقط یک دستور کوتاه بده.'],
    ['حرکت کنترل‌شده بده', 'حرکت واقعی از دستورهای ساده می‌آید: قدم زدن، چرخیدن، نفس کشیدن، مرتب کردن لباس یا گفتن یک راز. حرکت را به بخش‌های کوچک تقسیم کن تا دوربین فرصت پیدا کند فوکوس و کادر را حفظ کند.', 'از هر ژست ثابت، یک نسخه‌ی راه رفتن و یک نسخه‌ی واکنش طبیعی بساز. پایان حرکت را با مکث دو ثانیه‌ای ثبت کن.'],
  ] },
  { n: '۰۴', label: 'کار حرفه‌ای', title: 'ژست را با نور، دوربین و ایمنی کامل کن', color: 'var(--color-rose)', lessons: [
    ['زاویه دوربین را انتخاب کن', 'زاویه پایین شکوه می‌دهد، زاویه‌ی هم‌سطح صمیمیت می‌سازد و زاویه‌ی بالاتر لطافت و نظم را بیشتر می‌کند. زاویه را با شکل صورت و بدن هماهنگ کن، نه با یک قانون ثابت. قبل از تغییر ژست، یک تغییر کوچک در ارتفاع دوربین امتحان کن.', 'برای یک ژست سه ارتفاع تست کن: چشم، کمی پایین‌تر و کمی بالاتر. تفاوت خط فک، قد و پس‌زمینه را مقایسه کن.'],
    ['کادر و فضای حرکت', 'در جهت حرکت فضای خالی بگذار. معماری قرینه دوربین تراز می‌خواهد و در کادر عمودی، لباس و دست‌ها نباید بی‌دلیل قطع شوند. پیش از شاتر، چهار گوشه‌ی تصویر را چک کن و مطمئن شو خطوط مزاحم از سر و بدن عبور نمی‌کنند.', 'یک بار قاب را برای حرکت باز و یک بار برای پرتره ببند. اگر سوژه حرکت دارد، فضای جلوی نگاه و مسیر او را باز نگه دار.'],
    ['ایمنی و راحتی', 'دیپ، بلند کردن، پله، آب و سطح لغزنده فقط با کنترل، رضایت و نسخه‌ی ساده‌تر اجرا شوند. اگر سوژه درد، ترس یا بی‌تعادلی دارد، ژست ارزش ریسک ندارد. قبل از حرکت، مسیر پا و لباس را بررسی کن و یک نفر را مسئول مراقبت قرار بده.', 'برای هر ژست حرکتی یک جایگزین کم‌ریسک آماده کن: به جای بلند کردن، تکیه؛ به جای دویدن، قدم آهسته؛ به جای پله‌ی خیس، سطح خشک.'],
  ] },
];

const SOURCES = [
  ['Lindsay Adler، ساخت تنوع از ژست پایه', 'فرآیند ساخت چندین قاب از یک ژست پایه با تغییر نگاه، دست، فاصله و زاویه.', 'https://www.oreilly.com/library/view/the-photographers-guide/9781492018797/Text/chapter10.xhtml'],
  ['CreativeLive، Posing 101', 'مرجع کاربردی برای شانه، چانه، چشم، دست، پا، زوج و گروه.', 'https://www.creativelive.com/classes/posing-101-lindsay-adler'],
  ['Rangefinder، زبان بدن', 'بررسی رابطه‌ی حالت بدن و پیامی که عکس به مخاطب منتقل می‌کند.', 'https://rangefinderonline.com/news-features/tips-techniques/the-art-of-posing-body-language-basics/'],
  ['SLR Lounge، ژست طبیعی', 'حرکت‌های کوچک و کارگردانی واقعی به جای حالت مصنوعی و خشک.', 'https://www.slrlounge.com/simple-posing-guide-for-natural-authentic-portraits/'],
];

export const PrinciplesView: React.FC = () => {
  const [phase, setPhase] = useState(0);
  const [open, setOpen] = useState('0-0');
  const [openSource, setOpenSource] = useState<number | null>(null);
  const current = PHASES[phase];
  return (
    <div className="space-y-5">
      <SectionGuide section="principles" title="اصول ژست‌دهی چیست؟" text="این بخش یک راهنمای کامل و عملی است: صحنه را بخوان، بدن را بساز، از یک ژست تنوع بگیر و در پایان آن را با نور، کادر و ایمنی کامل کن." />
      <section className="relative pt-1">
        <div className="flex items-end justify-between gap-3"><div><span className="pill"><WandSparkles className="w-3 h-3 text-gold" /> مسیر یادگیری</span><h1 className="text-[24px] font-extrabold leading-tight mt-3">ژست حفظ نکن،<br /><span className="text-gold">ژست بساز.</span></h1></div><span className="text-[11px] text-muted">مرحله {phase + 1} از {PHASES.length}</span></div>
        <div className="mt-6 relative"><div className="absolute top-5 right-5 left-5 h-px bg-line" /><div className="relative flex justify-between">{PHASES.map((p, i) => <button key={p.n} onClick={() => { setPhase(i); setOpen(`${i}-0`); }} className="flex flex-col items-center gap-2" style={{ color: i === phase ? p.color : 'var(--color-faint)' }}><span className="w-10 h-10 rounded-full flex items-center justify-center border-2 text-[11px] font-extrabold" style={{ background: i <= phase ? `color-mix(in srgb, ${p.color} 16%, var(--color-bg))` : 'var(--color-bg)', borderColor: i <= phase ? p.color : 'var(--color-line)' }}>{i < phase ? <Check className="w-4 h-4" /> : p.n}</span><span className="text-[10px] font-bold">{p.label}</span></button>)}</div></div>
      </section>
      <section className="card p-4" style={{ borderColor: `color-mix(in srgb, ${current.color} 45%, var(--color-line))` }}><div className="flex items-start gap-3"><span className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0" style={{ background: `color-mix(in srgb, ${current.color} 17%, transparent)`, color: current.color }}><Target className="w-5 h-5" /></span><div><span className="text-[10px] font-extrabold" style={{ color: current.color }}>{current.label}</span><h2 className="text-[18px] font-extrabold mt-1">{current.title}</h2><p className="text-[12px] text-muted mt-2 leading-relaxed">هر درس را با یک قاب واقعی تمرین کن. هدف این نیست که متن را حفظ کنی، هدف این است که بتوانی دلیل انتخاب ژست و دستور خودت را توضیح بدهی.</p></div></div></section>
      <section className="relative mr-3 pr-5 border-r border-line space-y-3">{current.lessons.map((l, i) => { const id = `${phase}-${i}`; const is = open === id; return <div key={id} className="relative"><span className="absolute -right-[30px] top-4 w-3 h-3 rounded-full border-2" style={{ background: 'var(--color-bg)', borderColor: current.color }} /><div className="card overflow-hidden"><button onClick={() => setOpen(is ? '' : id)} className="w-full text-right p-4 flex items-center gap-3"><span className="text-[11px] font-extrabold" style={{ color: current.color }}>۰{i + 1}</span><span className="flex-1 font-extrabold text-[13px]">{l[0]}</span><ChevronDown className="w-4 h-4 text-faint" style={{ transform: is ? 'rotate(180deg)' : 'none' }} /></button>{is && <div className="px-4 pb-4 space-y-3 a-fade"><p className="text-[12.5px] leading-7 text-muted">{l[1]}</p><div className="p-3 rounded-2xl" style={{ background: `color-mix(in srgb, ${current.color} 10%, transparent)` }}><span className="text-[10px] font-extrabold flex items-center gap-1.5" style={{ color: current.color }}><Lightbulb className="w-3.5 h-3.5" /> تمرین سر صحنه</span><p className="text-[12px] leading-relaxed mt-1">{l[2]}</p></div></div>}</div></div>; })}</section>
      <div className="flex items-center justify-between gap-2"><button disabled={phase === 0} onClick={() => { setPhase(phase - 1); setOpen(`${phase - 1}-0`); }} className="btn btn-ghost disabled:opacity-40"><ArrowLeft className="w-4 h-4 rotate-180" /> مرحله قبل</button><button disabled={phase === PHASES.length - 1} onClick={() => { setPhase(phase + 1); setOpen(`${phase + 1}-0`); }} className="btn btn-primary disabled:opacity-40">مرحله بعد <ArrowLeft className="w-4 h-4" /></button></div>
      <section className="pt-3"><h2 className="font-extrabold text-[15px] flex items-center gap-2"><BookOpen className="w-4 h-4 text-gold" /> منابع منتخب</h2><p className="text-[11px] text-muted mt-1">برای مطالعه‌ی عمیق‌تر، هر منبع را باز کن.</p><div className="space-y-2 mt-3">{SOURCES.map((source, i) => { const is = openSource === i; return <div key={source[0]} className="rounded-2xl border border-line overflow-hidden"><button onClick={() => setOpenSource(is ? null : i)} className="w-full p-3 flex items-center gap-3 text-right"><span className="flex-1 text-[12px] font-bold">{source[0]}</span><ChevronDown className="w-4 h-4 text-faint" style={{ transform: is ? 'rotate(180deg)' : 'none' }} /></button>{is && <div className="px-3 pb-3 flex items-center gap-2"><p className="flex-1 text-[11px] text-muted leading-relaxed">{source[1]}</p><a href={source[2]} target="_blank" rel="noreferrer" className="p-2 rounded-xl" aria-label="باز کردن منبع"><ExternalLink className="w-4 h-4 text-gold" /></a></div>}</div>; })}</div></section>
    </div>
  );
};
